### ISSUE TITLE
Protobuf issue 

### ISSUE THREAD

**Issue by alaflaquiere** [axkoenig/grasp_refinement#4]
## Context
Trying to run trained agent container from a Windows 10 host with the command:
`docker-compose run grasp_refinement /bin/bash -c "source /home/catkin_ws/devel/setup.bash; python3 /home/catkin_ws/src/agent/src/main.py --output_dir=/home/.ros/log --train=0 --test_model_path=/home/catkin_ws/src/trained_agents/epsilon+delta_full --all_test_cases=0 --reward_framework=1 --contact_framework=1 --log_name=i_love_robots"`

## Error
```
[+] Running 1/0
 - Container grasp_refinement-novnc-1  Running                                                                                           0.0s
Traceback (most recent call last):
  File "/home/catkin_ws/src/agent/src/main.py", line 11, in <module>
    from stable_baselines3 import TD3, SAC, PPO, A2C
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/a2c/__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/a2c/a2c.py", line 7, in <module>
    from stable_baselines3.common.on_policy_algorithm import OnPolicyAlgorithm
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/on_policy_algorithm.py", line 8, in <module>
    from stable_baselines3.common.base_class import BaseAlgorithm
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/base_class.py", line 14, in <module>
    from stable_baselines3.common import utils
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/utils.py", line 14, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/tensorboard/__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

## Temporary solution
Export `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` in `docker-compose.yml`.

**Comment by axkoenig** [comment]
Hi, sorry for the very late response. Seems like you found a solution there! Please reach out if you have a permanent fix for this.
