### ISSUE TITLE
Missing /home/.ros/log directory

### ISSUE THREAD

**Issue by alaflaquiere** [axkoenig/grasp_refinement#5]
## Context
Trying to run trained agent container from a Windows 10 host with the command:
docker-compose run grasp_refinement /bin/bash -c "source /home/catkin_ws/devel/setup.bash; python3 /home/catkin_ws/src/agent/src/main.py --output_dir=/home/.ros/log --train=0 --test_model_path=/home/catkin_ws/src/trained_agents/epsilon+delta_full --all_test_cases=0 --reward_framework=1 --contact_framework=1 --log_name=i_love_robots"

## Error
```
[+] Running 1/0
 - Container grasp_refinement-novnc-1  Running                                                                                           0.0s
Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
... logging to /root/.ros/log/ebe05e3a-f6c4-11ec-a107-0242ac120003/roslaunch-91a3ac9f23cc-55.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://91a3ac9f23cc:35223/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)

auto-starting new master
process[master]: started with pid [72]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ebe05e3a-f6c4-11ec-a107-0242ac120003
process[rosout-1]: started with pid [90]
started core service [/rosout]
[INFO] [1656408618.473094]: Running with arguments
[INFO] [1656408618.476168]: - environment         refinement
[INFO] [1656408618.478731]: - train               0
[INFO] [1656408618.481110]: - seed                0
[INFO] [1656408618.483432]: - log_name            i_love_robots
process[gazebo-2]: started with pid [94]
[INFO] [1656408618.485519]: - output_dir          /home/.ros/log
[INFO] [1656408618.488112]: - chkpt_freq          300
[INFO] [1656408618.491351]: - check_env           0
process[gazebo_gui-3]: started with pid [102]
[INFO] [1656408618.494250]: - algorithm           sac
[INFO] [1656408618.496719]: - log_interval        1
[INFO] [1656408618.500221]: - all_test_cases      0
[INFO] [1656408618.503562]: - simplify_collisions 1
[INFO] [1656408618.507382]: - gui                 1
[INFO] [1656408618.509622]: - reward_framework    1
[INFO] [1656408618.512242]: - force_framework     1
[INFO] [1656408618.514624]: - torque_framework    3
[INFO] [1656408618.516886]: - w_eps_torque        5
[INFO] [1656408618.518958]: - w_delta             0.5
[INFO] [1656408618.521070]: - torque_noise        0.5
[INFO] [1656408618.523168]: - refine_steps        15
[INFO] [1656408618.525657]: - max_refine_rate     3
[INFO] [1656408618.528606]: - lift_steps          6
[INFO] [1656408618.531108]: - hold_steps          6
[INFO] [1656408618.533535]: - secs_to_lift        2
[INFO] [1656408618.535593]: - secs_to_hold        2
[INFO] [1656408618.537601]: - lift_dist           0.15
[INFO] [1656408618.539791]: - joint_lim           3
[INFO] [1656408618.542184]: - obj_shift_tol       0.1
[INFO] [1656408618.544298]: - time_steps          25000
[INFO] [1656408618.546784]: - x_error_min         -0.05
[INFO] [1656408618.549118]: - y_error_min         -0.05
[INFO] [1656408618.551332]: - z_error_min         -0.05
[INFO] [1656408618.553498]: - x_error_max         0.05
[INFO] [1656408618.555711]: - y_error_max         0.05
[INFO] [1656408618.557891]: - z_error_max         0.05
[INFO] [1656408618.559894]: - roll_error_min      -0.17453292519943295
[INFO] [1656408618.562392]: - pitch_error_min     -0.17453292519943295
[INFO] [1656408618.564972]: - yaw_error_min       -0.17453292519943295
[INFO] [1656408618.567025]: - roll_error_max      0.17453292519943295
[INFO] [1656408618.569187]: - pitch_error_max     0.17453292519943295
[INFO] [1656408618.571391]: - yaw_error_max       0.17453292519943295
[INFO] [1656408618.573427]: - gen_new_test_cases  0
[INFO] [1656408618.575599]: - eval_during_training0
[INFO] [1656408618.577682]: - eval_after_training 1
[INFO] [1656408618.579943]: - eval_freq           10
[INFO] [1656408618.582168]: - eval_after_episode  1
[INFO] [1656408618.584292]: - n_eval_episodes     10
[INFO] [1656408618.586960]: - eval_at_init        1
[INFO] [1656408618.590106]: - test_model_path     /home/catkin_ws/src/trained_agents/epsilon+delta_full
[INFO] [1656408618.592303]: - deterministic_eval  1
[INFO] [1656408618.594860]: - policy_delay        10
[INFO] [1656408618.597177]: - ent_coef            0.01
[INFO] [1656408618.599179]: - learning_starts     100
[INFO] [1656408618.601382]: - batch_size          64
[INFO] [1656408618.603620]: - gradient_steps      32
[INFO] [1656408618.605686]: - train_freq          32
[INFO] [1656408618.608095]: - learning_rate       0.0001
[INFO] [1656408618.610395]: - use_lr_schedule     0
[INFO] [1656408618.612742]: - tau                 0.0001
[INFO] [1656408618.615143]: - log_path            /home/.ros/log/logs/refinement
[INFO] [1656408618.617188]: - ckpt_path           /home/.ros/log/models/refinement/i_love_robots
[INFO] [1656408618.619691]: - model_path          /home/.ros/log/models/refinement/i_love_robots/final_model
[INFO] [1656408618.621900]: - best_model_path     /home/.ros/log/models/refinement/i_love_robots/best_model
[INFO] [1656408618.624296]: Making TEST environment...
Gazebo multi-robot simulator, version 11.8.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Wrn] [GuiIface.cc:200] g/gui-plugin is really loading a SystemPlugin. To load a GUI plugin please use --gui-client-plugin
Gazebo multi-robot simulator, version 11.8.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1656408619.268798649]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1656408619.272615435]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.18.0.3
[ INFO] [1656408619.408145329]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1656408619.411447018]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.18.0.3
[Wrn] [GuiIface.cc:298] Couldn't locate specified .ini. Creating file at "/root/.gazebo/gui.ini"
[Msg] Loading world file [/home/catkin_ws/src/reflex_simulator/description/worlds/reflex.world]
[Wrn] [GuiIface.cc:120] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[ INFO] [1656408619.736605168]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[Dbg] [DARTModel.cc:72] Initializing DART model ground_plane
[Dbg] [DARTModel.cc:128] Building DART BodyNode for link 'link' with a free joint.
Warning [BodyNode.cpp:469] [BodyNode] A negative or zero mass [0] is set to BodyNode [link], which can cause invalid physical behavior or segfault. Consider setting positive value instead.
[Dbg] [DARTPhysics.cc:751] Using BULLET collision detector
[ERROR] [1656408619.780271172]: ROS get_physics_properties service call does not yet support physics engine [dart].
[ INFO] [1656408619.821839831, 0.286000000]: Physics dynamic reconfigure ready.
[Wrn] [Publisher.cc:136] Queue limit reached for topic /gazebo/default/physics/contacts, deleting message. This warning is printed only once.
... logging to /root/.ros/log/ebe05e3a-f6c4-11ec-a107-0242ac120003/roslaunch-91a3ac9f23cc-43.log
[INFO] [1656408620.927681]: Your ActionSpace has 9 dimensions. Variable names are: dict_keys(['action_0', 'action_1', 'action_2', 'action_3', 'action_4', 'action_5', 'action_6', 'action_7', 'action_8'])
[INFO] [1656408620.928836]: Your ObservationSpace has 70 dimensions. Variable names are: dict_keys(['prox_angle_f1', 'dist_angle_f1', 'prox_angle_f2', 'dist_angle_f2', 'prox_angle_f3', 'dist_angle_f3', 'preshape_angle', 'contact_normal_p0_x', 'contact_normal_p0_y', 'contact_normal_p0_z', 'contact_pos_p0_x', 'contact_pos_p0_y', 'contact_pos_p0_z', 'contact_force_p0_x', 'contact_force_p0_y', 'contact_force_p0_z', 'contact_normal_p1_prox_x', 'contact_normal_p1_prox_y', 'contact_normal_p1_prox_z', 'contact_pos_p1_prox_x', 'contact_pos_p1_prox_y', 'contact_pos_p1_prox_z', 'contact_force_p1_prox_x', 'contact_force_p1_prox_y', 'contact_force_p1_prox_z', 'contact_normal_p1_dist_x', 'contact_normal_p1_dist_y', 'contact_normal_p1_dist_z', 'contact_pos_p1_dist_x', 'contact_pos_p1_dist_y', 'contact_pos_p1_dist_z', 'contact_force_p1_dist_x', 'contact_force_p1_dist_y', 'contact_force_p1_dist_z', 'contact_normal_p2_prox_x', 'contact_normal_p2_prox_y', 'contact_normal_p2_prox_z', 'contact_pos_p2_prox_x', 'contact_pos_p2_prox_y', 'contact_pos_p2_prox_z', 'contact_force_p2_prox_x', 'contact_force_p2_prox_y', 'contact_force_p2_prox_z', 'contact_normal_p2_dist_x', 'contact_normal_p2_dist_y', 'contact_normal_p2_dist_z', 'contact_pos_p2_dist_x', 'contact_pos_p2_dist_y', 'contact_pos_p2_dist_z', 'contact_force_p2_dist_x', 'contact_force_p2_dist_y', 'contact_force_p2_dist_z', 'contact_normal_p3_prox_x', 'contact_normal_p3_prox_y', 'contact_normal_p3_prox_z', 'contact_pos_p3_prox_x', 'contact_pos_p3_prox_y', 'contact_pos_p3_prox_z', 'contact_force_p3_prox_x', 'contact_force_p3_prox_y', 'contact_force_p3_prox_z', 'contact_normal_p3_dist_x', 'contact_normal_p3_dist_y', 'contact_normal_p3_dist_z', 'contact_pos_p3_dist_x', 'contact_pos_p3_dist_y', 'contact_pos_p3_dist_z', 'contact_force_p3_dist_x', 'contact_force_p3_dist_y', 'contact_force_p3_dist_z'])
[INFO] [1656408620.942468]: Rate lift is:       3.000000
[INFO] [1656408620.943404]: Rate hold is:       3.000000
[INFO] [1656408620.944238]: Min values of ActionSpace are [-1, -1, -1, -1, -1, -1, -1, -1, -1].
[INFO] [1656408620.944698]: Max values of ActionSpace are [1, 1, 1, 1, 1, 1, 1, 1, 1].
[INFO] [1656408620.945534]: Min values of ObservationSpace are [-0.01, -0.01, -0.01, -0.01, -0.01, -0.01, 0, -1, -1, 0, -0.095, -0.07200000000000001, 0.04000000000000001, -20, -20, -20, -1, -1, -1, -0.2, -0.3, 0.05, -20, -20, -20, -1, -1, -1, -0.2, -0.3, 0.05, -20, -20, -20, -1, -1, -1, -0.2, -0.3, 0.05, -20, -20, -20, -1, -1, -1, -0.2, -0.3, 0.05, -20, -20, -20, -1, -1, -1, -0.2, -0.3, 0.05, -20, -20, -20, -1, -1, -1, -0.2, -0.3, 0.05, -20, -20, -20].
[INFO] [1656408620.945892]: Max values of ObservationSpace are [3, 0.6000000000000001, 3, 0.6000000000000001, 3, 0.6000000000000001, 1.5707963267948966, 1, 1, 1, 0.095, 0.07200000000000001, 0.1, 20, 20, 20, 1, 1, 1, 0.2, 0.3, 0.3, 20, 20, 20, 1, 1, 1, 0.2, 0.3, 0.3, 20, 20, 20, 1, 1, 1, 0.2, 0.3, 0.3, 20, 20, 20, 1, 1, 1, 0.2, 0.3, 0.3, 20, 20, 20, 1, 1, 1, 0.2, 0.3, 0.3, 20, 20, 20, 1, 1, 1, 0.2, 0.3, 0.3, 20, 20, 20].
/usr/local/lib/python3.8/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
[INFO] [1656408620.948721]: Loading model from: /home/catkin_ws/src/trained_agents/epsilon+delta_full
[INFO] [1656408621.479321]: Testing model...
Traceback (most recent call last):
  File "/home/catkin_ws/src/agent/src/main.py", line 164, in <module>
    main(args)
  File "/home/catkin_ws/src/agent/src/main.py", line 156, in main
    test(model, env, log_path, "test_" + args.log_name, hparams["deterministic_eval"], hparams["all_test_cases"])
  File "/home/catkin_ws/src/agent/src/controller/tests.py", line 299, in test
    with open(path, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/.ros/log/logs/refinement/test_i_love_robots.csv'
```

## Tentative solution
Add the log directory to the repo, or provide correct path to csv file.

**Comment by axkoenig** [comment]
Hi there, again sorry for replying so late. I was not monitoring this repo closely in the summer. Thanks for reporting the bug. I added this [commit](https://github.com/axkoenig/grasp_refinement/commit/12f7aa7561ba6dd90b1a27c87988fa3284491e9d) to fix it. It should work now :-)
Feel free to re-open if there are other related problems!
